// Clinic-ready PDF renderer for a Stackd Insights object. Ships the same
// numbers computeInsights produced — one renderer for download and email.

import { jsPDF } from "npm:jspdf@4.0.0";

const DISCLAIMER = "Describes your CGM data. Not medical advice. Not a dose recommendation.";
const FOOTER_2 = "Generated by Stackd from the user's connected Dexcom CGM data.";

const INRANGE = [41, 101, 80];
const VERY_LOW = [178, 84, 76];
const LOW = [201, 133, 95];
const HIGH = [181, 148, 63];
const VERY_HIGH = [156, 82, 40];

function bandRGB(key) {
  if (key === "veryLow") return VERY_LOW;
  if (key === "low") return LOW;
  if (key === "high") return HIGH;
  if (key === "veryHigh") return VERY_HIGH;
  return INRANGE; // target
}

export function renderInsightsPdf(insights) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth(); // 595pt
  const H = doc.internal.pageSize.getHeight();
  const M = 40;
  let y = 0;

  const ensureFooter = () => {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(90, 87, 78);
      doc.text(DISCLAIMER, M, H - 38, { maxWidth: W - 2 * M, align: "center" });
      doc.text(FOOTER_2, M, H - 24, { maxWidth: W - 2 * M, align: "center" });
    }
  };

  const ensureSpace = (needed) => {
    if (y + needed > H - 60) {
      doc.addPage();
      y = M + 20;
    }
  };

  const fmtDate = (iso) => {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return "-";
    return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  };

  // ── Header ───────────────────────────────────────────────────────────
  y = M;
  doc.setFillColor(76, 103, 112);
  doc.rect(0, 0, W, 84, "F");
  doc.setTextColor(247, 241, 232);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Stackd Insights Report", M, 40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(insights.meta?.displayName || "Stackd user", M, 60);

  y = 108;
  doc.setTextColor(63, 56, 48);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Report details", M, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y += 18;
  const rows = [
    ["Date range", `${fmtDate(insights.rangeStart)} — ${fmtDate(insights.rangeEnd)}`],
    ["Date generated", fmtDate(insights.meta?.generatedAt)],
    ["System", insights.meta?.cgmSystem || "Dexcom"],
    ["Window", `${insights.windowDays} days`],
  ];
  for (const [k, v] of rows) {
    doc.setFont("helvetica", "bold");
    doc.text(k + ":", M, y);
    doc.setFont("helvetica", "normal");
    const kw = doc.getTextWidth(k + ":");
    doc.text(v, M + kw + 8, y);
    y += 16;
  }

  // ── Key stats table ──────────────────────────────────────────────────
  ensureSpace(90);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Key statistics", M, y);
  y += 16;

  const stats = [];
  if (insights.gates?.passTir) {
    stats.push(["GMI", `${insights.tir.gmi} %`]);
    stats.push(["Mean glucose", `${insights.tir.mean} mg/dL`]);
    stats.push(["Standard deviation", `${insights.tir.sd} mg/dL`]);
  } else {
    stats.push(["GMI", insights.gates.tirMessage]);
    stats.push(["Mean glucose", insights.gates.tirMessage]);
    stats.push(["Standard deviation", insights.gates.tirMessage]);
  }
  if (insights.gates?.passCv) {
    stats.push(["%CV", `${insights.tir.cv} %`]);
  } else {
    stats.push(["%CV", insights.gates.cvMessage]);
  }
  stats.push(["Days with data", `${insights.sensor.daysWithData} of ${insights.windowDays}`]);
  stats.push(["Readings captured", `${insights.sensor.percentCaptured} %`]);

  const colX = M;
  const colW = (W - 2 * M - 30) / 2;
  let col2X = M + colW + 30;
  for (let i = 0; i < stats.length; i++) {
    const [k, v] = stats[i];
    const x = i % 2 === 0 ? colX : col2X;
    if (i % 2 === 0) ensureSpace(40);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(106, 97, 83);
    doc.text(k, x, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(63, 56, 48);
    doc.text(v, x, y + 16);
    if (i % 2 === 1) y += 42;
  }
  y += 20;

  // ── TIR band bar ─────────────────────────────────────────────────────
  ensureSpace(150);
  doc.setTextColor(63, 56, 48);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Time in range", M, y);
  y += 14;

  const bandPcts = insights.tir?.bandPercentages || [];
  const barW = W - 2 * M;
  const barH = 34;
  const segX0 = M;
  let cx = segX0;
  for (const band of bandPcts) {
    const segW = (band.percent / 100) * barW;
    if (segW > 0.5) {
      doc.setFillColor(...bandRGB(band.key));
      doc.rect(cx, y, segW, barH, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      const label = band.percent + "%";
      if (segW > doc.getTextWidth(label) + 12) {
        doc.text(label, cx + segW / 2, y + 22, { align: "center" });
      }
    }
    cx += segW;
  }
  y += barH + 8;

  // Legend
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  let lx = M;
  for (const band of bandPcts) {
    doc.setFillColor(...bandRGB(band.key));
    doc.rect(lx, y - 6, 10, 10, "F");
    doc.setTextColor(63, 56, 48);
    doc.text(`${band.label} (${band.percent}%)`, lx + 14, y + 1);
    lx += 14 + doc.getTextWidth(`${band.label} (${band.percent}%)`) + 14;
  }
  y += 20;

  if (!insights.gates?.passTir) {
    doc.setTextColor(90, 87, 78);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.text(insights.gates.tirMessage, M, y);
    y += 16;
  } else {
    doc.setTextColor(63, 56, 48);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Mean ${insights.tir.mean} mg/dL · SD ${insights.tir.sd} · ${insights.tir.variabiltyNote}`, M, y);
    y += 16;
  }

  // ── Hour-of-day curve ────────────────────────────────────────────────
  ensureSpace(220);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(63, 56, 48);
  doc.text("Glucose by hour of day (median)", M, y);
  y += 12;

  const curveW = W - 2 * M;
  const curveH = 120;
  const baseY = y + curveH;
  const chartTop = y;
  const minV = 40, maxV = 280;
  const series = insights.hourMedian || [];

  // Target band 70-180 shaded.
  const targetTop = chartTop + curveH * (1 - (180 - minV) / (maxV - minV));
  const targetBottom = chartTop + curveH * (1 - (70 - minV) / (maxV - minV));
  doc.setFillColor(93, 101, 80, 0.12);
  doc.rect(M, targetTop, curveW, targetBottom - targetTop, "F");
  doc.setDrawColor(93, 101, 80, 0.4);
  doc.setLineWidth(0.7);
  doc.line(M, targetTop, M + curveW, targetTop);
  doc.line(M, targetBottom, M + curveW, targetBottom);

  // Axis labels
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(106, 97, 83);
  doc.text("70–180 target", M, targetTop - 4);

  const px = (h) => M + (h / 24) * curveW;
  const py = (v) => chartTop + curveH * (1 - (v - minV) / (maxV - minV));

  doc.setDrawColor(63, 56, 48);
  doc.setLineWidth(1.4);
  const pts = [];
  series.forEach((v, h) => {
    if (v != null) pts.push([px(h), py(Math.min(Math.max(v, minV), maxV))]);
  });
  for (let i = 1; i < pts.length; i++) {
    const [x1, y1] = pts[i - 1];
    const [x2, y2] = pts[i];
    if (x1 != null && x2 != null) doc.line(x1, y1, x2, y2);
  }

  // Hour ticks
  doc.setTextColor(106, 97, 83);
  doc.setFontSize(7);
  for (let h = 0; h <= 24; h += 6) {
    doc.text(h === 24 ? "24" : String(h), px(h) - 3, baseY + 10);
  }
  y = baseY + 16;

  // ── Patterns ─────────────────────────────────────────────────────────
  ensureSpace(120);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(63, 56, 48);
  doc.text("Recurring glucose patterns", M, y);
  y += 16;

  if (!insights.patterns.length) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(90, 87, 78);
    doc.text(insights.gates.passTir ? "No recurring patterns detected in this window." : insights.gates.tirMessage, M, y);
    y += 16;
  } else {
    for (const p of insights.patterns) {
      ensureSpace(52);
      const kind = p.type === "high" ? "Times above target" : "Times below target";
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(p.type === "high" ? [171, 117, 26] : [178, 84, 76]);
      doc.text(`${kind} · mostly ${p.windowLabel}`, M, y);
      y += 14;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(63, 56, 48);
      doc.text(`${p.count} of ${p.ofDays} days, mostly between ${p.windowLabel}`, M, y);
      y += 14;
      if (p.evidenceDates && p.evidenceDates.length) {
        doc.setFontSize(8);
        doc.setTextColor(106, 97, 83);
        doc.text("Seen on: " + p.evidenceDates.map(fmtDate).join(", "), M, y, { maxWidth: W - 2 * M });
        y += 18;
      }
    }
  }

  // ── Best day ─────────────────────────────────────────────────────────
  ensureSpace(70);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(63, 56, 48);
  doc.text("Best day in range", M, y);
  y += 16;
  if (insights.bestDay) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`${fmtDate(insights.bestDay.date + "T12:00:00")} — ${insights.bestDay.tirPercent}% time in target`, M, y);
  } else {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(90, 87, 78);
    doc.text("Not enough data yet.", M, y);
  }

  if (insights.gates?.passCv && insights.tir?.variabiltyNote) {
    ensureSpace(30);
    doc.setFontSize(9);
    doc.setTextColor(106, 97, 83);
    doc.text(insights.tir.variabiltyNote, M, y + 8);
  }

  ensureFooter();

  // Return base64 (data URI without prefix) for attaching/downloading.
  const b64 = doc.output("datauristring").split(",")[1];
  return b64;
}